// Convert snarkjs (BLS12-381) vkey/proof/public JSON into a Rust fixture of raw
// byte arrays in the encoding molfi-verifier expects:
//   G1Affine = x(48 BE) || y(48 BE)          (96 bytes)
//   G2Affine = Fp2(x) || Fp2(y)              (192 bytes)
//   Fp2      = c?(48 BE) || c?(48 BE)         order set by G2_ORDER
//   Fr       = 32-byte BE                      (public signals)
//
// Usage: node scripts/to_soroban.mjs <circuit> [outPath]
// Env:   G2_ORDER = "c1c0" (default) | "c0c1"
import fs from "fs";

const circuit = process.argv[2];
const outPath = process.argv[3] || `build/${circuit}/fixture.rs`;
const G2_ORDER = process.env.G2_ORDER || "c1c0";
const B = `build/${circuit}`;

const vk = JSON.parse(fs.readFileSync(`${B}/vkey.json`));
const proof = JSON.parse(fs.readFileSync(`${B}/proof.json`));
const pub = JSON.parse(fs.readFileSync(`${B}/public.json`));

function toBE(dec, len) {
  let h = BigInt(dec).toString(16);
  if (h.length % 2) h = "0" + h;
  let bytes = h === "0" ? [0] : (h.match(/.{2}/g) || []).map((x) => parseInt(x, 16));
  while (bytes.length < len) bytes.unshift(0);
  if (bytes.length > len) throw new Error(`value too large for ${len} bytes`);
  return bytes;
}
const g1 = (p) => [...toBE(p[0], 48), ...toBE(p[1], 48)];
const fp2 = (a) =>
  G2_ORDER === "c1c0"
    ? [...toBE(a[1], 48), ...toBE(a[0], 48)]
    : [...toBE(a[0], 48), ...toBE(a[1], 48)];
const g2 = (p) => [...fp2(p[0]), ...fp2(p[1])];
const fr = (s) => toBE(s, 32);
const lit = (bytes) => `[${bytes.join(",")}]`;

let out = "// AUTO-GENERATED by molfi-circuits/scripts/to_soroban.mjs — do not edit.\n";
out += `// circuit=${circuit} G2_ORDER=${G2_ORDER}\n`;
out += `pub const VK_ALPHA: [u8; 96] = ${lit(g1(vk.vk_alpha_1))};\n`;
out += `pub const VK_BETA: [u8; 192] = ${lit(g2(vk.vk_beta_2))};\n`;
out += `pub const VK_GAMMA: [u8; 192] = ${lit(g2(vk.vk_gamma_2))};\n`;
out += `pub const VK_DELTA: [u8; 192] = ${lit(g2(vk.vk_delta_2))};\n`;
out += `pub const VK_IC: [[u8; 96]; ${vk.IC.length}] = [${vk.IC.map((p) => lit(g1(p))).join(",\n")}];\n`;
out += `pub const PROOF_A: [u8; 96] = ${lit(g1(proof.pi_a))};\n`;
out += `pub const PROOF_B: [u8; 192] = ${lit(g2(proof.pi_b))};\n`;
out += `pub const PROOF_C: [u8; 96] = ${lit(g1(proof.pi_c))};\n`;
out += `pub const PUBLIC: [[u8; 32]; ${pub.length}] = [${pub.map((s) => lit(fr(s))).join(",\n")}];\n`;

fs.writeFileSync(outPath, out);
console.log(`wrote ${outPath} (G2_ORDER=${G2_ORDER}, IC=${vk.IC.length}, public=${pub.length})`);
