//! End-to-end integration tests wiring the full Molfi contract suite together:
//! token (SAC) + market + clob-settlement + verifier + privacy-pool.
//!
//! ZK proofs are checked by a `MockVerifier` (always-accepts) so the economic
//! and cross-contract wiring can be exercised without circuit artifacts. The
//! real `molfi-verifier` keeps its own crypto unit tests; swapping the mock for
//! the real verifier + a valid proof is the only change for production.

use ed25519_dalek::{Signer, SigningKey};
use soroban_sdk::{
    contract, contractimpl, symbol_short,
    testutils::{Address as _, Ledger},
    token::{StellarAssetClient, TokenClient},
    Address, BytesN, Env, String, Symbol, Vec,
};

use molfi_clob_settlement::{ClobSettlement, ClobSettlementClient, Order};
use molfi_market::{Asset, MarketContract, MarketContractClient, PriceData};
use molfi_privacy_pool::{PrivacyPool, PrivacyPoolClient};

// Real BLS12-381 Groth16 verifying key + proof for the `withdraw` (Poseidon
// Merkle membership + nullifier) circuit, generated by molfi-circuits/.
mod withdraw_fixture {
    include!("groth16_withdraw_fixture.rs");
}

// ── Always-accepting verifier stand-in ──────────────────────────────────────
#[contract]
pub struct MockVerifier;

#[contractimpl]
impl MockVerifier {
    pub fn verify(
        _env: Env,
        _proof: molfi_verifier::Proof,
        _public_inputs: Vec<BytesN<32>>,
        _domain: BytesN<32>,
    ) -> bool {
        true
    }
}

// ── SEP-40 price-oracle stand-in (mimics Reflector) ─────────────────────────
#[contract]
pub struct MockOracle;

#[contractimpl]
impl MockOracle {
    pub fn __constructor(env: Env, price: i128, timestamp: u64) {
        env.storage().instance().set(&symbol_short!("price"), &price);
        env.storage().instance().set(&symbol_short!("ts"), &timestamp);
    }
    pub fn lastprice(env: Env, _asset: Asset) -> Option<PriceData> {
        let price: i128 = env.storage().instance().get(&symbol_short!("price")).unwrap();
        let timestamp: u64 = env.storage().instance().get(&symbol_short!("ts")).unwrap();
        Some(PriceData { price, timestamp })
    }
    pub fn decimals(_env: Env) -> u32 {
        14
    }
}

const PRICE_SCALE: i128 = 100_000_000_000_000; // 1e14, Reflector's 14 decimals

fn zero_bytes<const N: usize>(env: &Env) -> BytesN<N> {
    BytesN::from_array(env, &[0u8; N])
}

/// i128 as a 32-byte big-endian field element (matches the pool's binding).
fn amount_field(env: &Env, amount: i128) -> BytesN<32> {
    let mut out = [0u8; 32];
    out[16..].copy_from_slice(&amount.to_be_bytes());
    BytesN::from_array(env, &out)
}

fn market_proof(env: &Env) -> molfi_market::Proof {
    molfi_market::Proof {
        a: zero_bytes::<96>(env),
        b: zero_bytes::<192>(env),
        c: zero_bytes::<96>(env),
    }
}

fn pool_proof(env: &Env) -> molfi_privacy_pool::Proof {
    molfi_privacy_pool::Proof {
        a: zero_bytes::<96>(env),
        b: zero_bytes::<192>(env),
        c: zero_bytes::<96>(env),
    }
}

/// Build an ed25519-signed order whose signature matches the contract's
/// canonical byte layout exactly.
#[allow(clippy::too_many_arguments)]
fn signed_order(
    env: &Env,
    seed: [u8; 32],
    market: [u8; 32],
    addr: &Address,
    outcome: u32,
    price: u32,
    size: i128,
    nonce: u64,
    expiry: u64,
) -> Order {
    let sk = SigningKey::from_bytes(&seed);
    let pk = sk.verifying_key().to_bytes();

    // market(32) ‖ pubkey(32) ‖ outcome(4) ‖ price(4) ‖ size(16) ‖ nonce(8) ‖ expiry(8)
    let mut msg = std::vec::Vec::new();
    msg.extend_from_slice(&market);
    msg.extend_from_slice(&pk);
    msg.extend_from_slice(&outcome.to_be_bytes());
    msg.extend_from_slice(&price.to_be_bytes());
    msg.extend_from_slice(&size.to_be_bytes());
    msg.extend_from_slice(&nonce.to_be_bytes());
    msg.extend_from_slice(&expiry.to_be_bytes());

    let sig = sk.sign(&msg).to_bytes();

    Order {
        maker_pubkey: BytesN::from_array(env, &pk),
        maker_addr: addr.clone(),
        market: BytesN::from_array(env, &market),
        outcome,
        price,
        size,
        nonce,
        expiry,
        signature: BytesN::from_array(env, &sig),
    }
}

#[test]
fn bet_on_market_settle_and_win() {
    let env = Env::default();
    env.mock_all_auths();
    env.ledger().set_timestamp(1_000);

    let admin = Address::generate(&env);
    let relayer = Address::generate(&env);

    // Collateral token (SAC).
    let sac = env.register_stellar_asset_contract_v2(admin.clone());
    let token_addr = sac.address();
    let mint = StellarAssetClient::new(&env, &token_addr);
    let tok = TokenClient::new(&env, &token_addr);

    // Verifier (mock), market, settlement.
    let verifier = env.register(MockVerifier, ());
    let market = env.register(MarketContract, (admin.clone(), verifier.clone()));
    let market_c = MarketContractClient::new(&env, &market);
    let settle = env.register(
        ClobSettlement,
        (admin.clone(), relayer, token_addr.clone(), market.clone()),
    );
    let settle_c = ClobSettlementClient::new(&env, &settle);

    // Create the market.
    let mkt = [9u8; 32];
    let mkt_id = BytesN::from_array(&env, &mkt);
    market_c.create(&mkt_id, &String::from_str(&env, "Will it rain tomorrow?"), &2_000);

    // Two traders take opposite sides. Alice bets YES @0.60, Bob bets NO @0.40.
    let alice = Address::generate(&env);
    let bob = Address::generate(&env);
    mint.mint(&alice, &60_000_000); // 60.0
    mint.mint(&bob, &40_000_000); // 40.0

    // Traders fund the settlement contract (CLOB account model).
    settle_c.deposit(&alice, &60_000_000);
    settle_c.deposit(&bob, &40_000_000);
    assert_eq!(tok.balance(&alice), 0, "alice's collateral deposited");
    assert_eq!(tok.balance(&bob), 0, "bob's collateral deposited");
    assert_eq!(tok.balance(&settle), 100_000_000, "contract holds collateral");

    let alice_order = signed_order(&env, [1u8; 32], mkt, &alice, 0, 600_000, 100, 1, 9_999);
    let bob_order = signed_order(&env, [2u8; 32], mkt, &bob, 1, 400_000, 100, 1, 9_999);

    // ── Settlement ──
    settle_c.settle(&alice_order, &bob_order, &100);

    assert_eq!(settle_c.escrow(&mkt_id), 100_000_000, "pot fully escrowed");
    assert_eq!(settle_c.balance(&alice), 0, "alice's funded balance spent");
    assert_eq!(settle_c.balance(&bob), 0, "bob's funded balance spent");
    assert_eq!(settle_c.position(&alice, &mkt_id, &0), 100, "alice holds 100 YES");
    assert_eq!(settle_c.position(&bob, &mkt_id, &1), 100, "bob holds 100 NO");

    // ── Resolution via the ZK proof path ──
    env.ledger().set_timestamp(2_500);
    market_c.begin_resolution(&mkt_id);
    market_c.resolve_with_proof(&mkt_id, &0 /* YES */, &market_proof(&env), &zero_bytes::<32>(&env));
    assert_eq!(market_c.winning_outcome(&mkt_id), 0);

    // ── Alice redeems the pot (the win) ──
    let payout = settle_c.redeem(&alice, &mkt_id, &100);
    assert_eq!(payout, 100_000_000);
    assert_eq!(tok.balance(&alice), 100_000_000, "alice won the whole pot");
    assert_eq!(settle_c.escrow(&mkt_id), 0, "escrow drained");
    assert_eq!(settle_c.position(&alice, &mkt_id, &0), 0, "position consumed");

    // Net result: Alice staked 60, won 100 → +40 profit. Bob lost his 40.
    assert_eq!(tok.balance(&bob), 0);

    // ── Loser cannot redeem (holds NO, not the winning YES) ──
    let bad = settle_c.try_redeem(&bob, &mkt_id, &100);
    assert!(bad.is_err(), "NO holder can't claim a YES win");
}

#[test]
fn settle_rejects_replayed_nonce() {
    let env = Env::default();
    env.mock_all_auths();
    env.ledger().set_timestamp(1_000);

    let admin = Address::generate(&env);
    let relayer = Address::generate(&env);
    let sac = env.register_stellar_asset_contract_v2(admin.clone());
    let token_addr = sac.address();
    let mint = StellarAssetClient::new(&env, &token_addr);
    let verifier = env.register(MockVerifier, ());
    let market = env.register(MarketContract, (admin.clone(), verifier.clone()));
    let settle = env.register(
        ClobSettlement,
        (admin.clone(), relayer, token_addr.clone(), market),
    );
    let settle_c = ClobSettlementClient::new(&env, &settle);

    let mkt = [3u8; 32];
    let alice = Address::generate(&env);
    let bob = Address::generate(&env);
    mint.mint(&alice, &120_000_000);
    mint.mint(&bob, &80_000_000);
    settle_c.deposit(&alice, &120_000_000);
    settle_c.deposit(&bob, &80_000_000);

    let a1 = signed_order(&env, [1u8; 32], mkt, &alice, 0, 600_000, 100, 7, 9_999);
    let b1 = signed_order(&env, [2u8; 32], mkt, &bob, 1, 400_000, 100, 8, 9_999);
    settle_c.settle(&a1, &b1, &100);

    // Re-submitting the same maker nonce must fail.
    let a2 = signed_order(&env, [1u8; 32], mkt, &alice, 0, 600_000, 100, 7, 9_999);
    let b2 = signed_order(&env, [2u8; 32], mkt, &bob, 1, 400_000, 100, 9, 9_999);
    assert!(settle_c.try_settle(&a2, &b2, &100).is_err());
}

#[test]
fn privacy_pool_confidential_round_trip() {
    let env = Env::default();
    env.mock_all_auths();

    let admin = Address::generate(&env);
    let sac = env.register_stellar_asset_contract_v2(admin.clone());
    let token_addr = sac.address();
    let mint = StellarAssetClient::new(&env, &token_addr);
    let tok = TokenClient::new(&env, &token_addr);

    let verifier = env.register(MockVerifier, ());
    let pool = env.register(PrivacyPool, (admin.clone(), verifier, token_addr.clone()));
    let pool_c = PrivacyPoolClient::new(&env, &pool);

    let alice = Address::generate(&env);
    mint.mint(&alice, &100_000_000);

    // Confidential deposit.
    let commitment = BytesN::from_array(&env, &[5u8; 32]);
    pool_c.deposit(&alice, &commitment, &100_000_000);
    assert_eq!(tok.balance(&alice), 0);
    assert_eq!(tok.balance(&pool), 100_000_000);
    assert_eq!(pool_c.leaf_count(), 1);

    // Private, proof-gated withdrawal. public_signals = [root, nullifierHash, ...].
    let root = pool_c.root();
    let nullifier = BytesN::from_array(&env, &[7u8; 32]);
    let mut sigs = Vec::new(&env);
    sigs.push_back(root.clone());
    sigs.push_back(nullifier.clone());
    sigs.push_back(zero_bytes::<32>(&env)); // recipient signal
    sigs.push_back(amount_field(&env, 100_000_000)); // amount signal (bound)
    pool_c.withdraw(&pool_proof(&env), &sigs, &alice, &100_000_000);
    assert_eq!(tok.balance(&alice), 100_000_000);
    assert!(pool_c.is_nullifier_used(&nullifier));

    // Double-spend of the same nullifier is rejected.
    let replay = pool_c.try_withdraw(&pool_proof(&env), &sigs, &alice, &100_000_000);
    assert!(replay.is_err());
}

#[test]
fn btc_market_resolves_via_oracle_and_pays_winner() {
    let env = Env::default();
    env.mock_all_auths();
    env.ledger().set_timestamp(1_000);

    let admin = Address::generate(&env);
    let relayer = Address::generate(&env);

    let sac = env.register_stellar_asset_contract_v2(admin.clone());
    let token_addr = sac.address();
    let mint = StellarAssetClient::new(&env, &token_addr);
    let tok = TokenClient::new(&env, &token_addr);

    let verifier = env.register(MockVerifier, ());
    let market = env.register(MarketContract, (admin.clone(), verifier.clone()));
    let market_c = MarketContractClient::new(&env, &market);
    let settle = env.register(
        ClobSettlement,
        (admin.clone(), relayer, token_addr.clone(), market.clone()),
    );
    let settle_c = ClobSettlementClient::new(&env, &settle);

    // Reflector-style oracle reporting BTC = $105,000 (priced at t=1,500).
    let btc_price = 105_000 * PRICE_SCALE;
    let oracle = env.register(MockOracle, (btc_price, 1_500u64));

    // "Will BTC be ≥ $100k at close?" — settled from the oracle.
    let mkt = [0xb7u8; 32];
    let mkt_id = BytesN::from_array(&env, &mkt);
    let threshold = 100_000 * PRICE_SCALE;
    market_c.create_price_market(
        &mkt_id,
        &String::from_str(&env, "Will BTC be >= $100k at close?"),
        &2_000,
        &oracle,
        &Asset::Other(Symbol::new(&env, "BTC")),
        &threshold,
        &0, // OP_GTE
        &86_400,
    );

    // Alice bets YES @0.60, Bob bets NO @0.40 (100 shares).
    let alice = Address::generate(&env);
    let bob = Address::generate(&env);
    mint.mint(&alice, &60_000_000);
    mint.mint(&bob, &40_000_000);
    settle_c.deposit(&alice, &60_000_000);
    settle_c.deposit(&bob, &40_000_000);

    let a = signed_order(&env, [11u8; 32], mkt, &alice, 0, 600_000, 100, 1, 9_999);
    let b = signed_order(&env, [12u8; 32], mkt, &bob, 1, 400_000, 100, 1, 9_999);
    settle_c.settle(&a, &b, &100);
    assert_eq!(settle_c.escrow(&mkt_id), 100_000_000);

    // ── Oracle settlement (permissionless, after close) ──
    env.ledger().set_timestamp(2_500);
    let outcome = market_c.resolve_from_oracle(&mkt_id);
    assert_eq!(outcome, 0, "BTC 105k >= 100k → YES");
    assert!(market_c.is_resolved(&mkt_id));

    // Alice (YES) collects the pot.
    let payout = settle_c.redeem(&alice, &mkt_id, &100);
    assert_eq!(payout, 100_000_000);
    assert_eq!(tok.balance(&alice), 100_000_000, "YES bettor won via oracle settlement");
}

#[test]
fn oracle_resolves_no_when_below_threshold() {
    let env = Env::default();
    env.mock_all_auths();
    env.ledger().set_timestamp(1_000);

    let admin = Address::generate(&env);
    let verifier = env.register(MockVerifier, ());
    let market = env.register(MarketContract, (admin.clone(), verifier));
    let market_c = MarketContractClient::new(&env, &market);

    // BTC = $105k, but the market asks ≥ $200k → NO.
    let oracle = env.register(MockOracle, (105_000 * PRICE_SCALE, 1_500u64));
    let mkt_id = BytesN::from_array(&env, &[0xb8u8; 32]);
    market_c.create_price_market(
        &mkt_id,
        &String::from_str(&env, "Will BTC be >= $200k at close?"),
        &2_000,
        &oracle,
        &Asset::Other(Symbol::new(&env, "BTC")),
        &(200_000 * PRICE_SCALE),
        &0,
        &86_400,
    );

    env.ledger().set_timestamp(2_500);
    assert_eq!(market_c.resolve_from_oracle(&mkt_id), 1, "105k < 200k → NO");
}

#[test]
fn oracle_rejects_stale_price() {
    let env = Env::default();
    env.mock_all_auths();
    env.ledger().set_timestamp(1_000);

    let admin = Address::generate(&env);
    let verifier = env.register(MockVerifier, ());
    let market = env.register(MarketContract, (admin.clone(), verifier));
    let market_c = MarketContractClient::new(&env, &market);

    // Price stamped at t=10 with a 100s staleness window; resolving at t=2500 is stale.
    let oracle = env.register(MockOracle, (105_000 * PRICE_SCALE, 10u64));
    let mkt_id = BytesN::from_array(&env, &[0xb9u8; 32]);
    market_c.create_price_market(
        &mkt_id,
        &String::from_str(&env, "stale?"),
        &2_000,
        &oracle,
        &Asset::Other(Symbol::new(&env, "BTC")),
        &(100_000 * PRICE_SCALE),
        &0,
        &100,
    );

    env.ledger().set_timestamp(2_500);
    assert!(market_c.try_resolve_from_oracle(&mkt_id).is_err(), "stale price rejected");
}

#[test]
fn confidential_withdraw_with_real_proof() {
    // The full privacy-pool exit, end to end, gated by a REAL Groth16
    // membership + nullifier proof verified on-chain by the real verifier:
    // deposit collateral -> operator checkpoints the Merkle root -> a private
    // withdrawal unlocks funds against a genuine proof -> nullifier burned.
    use withdraw_fixture as f;
    let env = Env::default();
    env.mock_all_auths();

    let admin = Address::generate(&env);
    let sac = env.register_stellar_asset_contract_v2(admin.clone());
    let token_addr = sac.address();
    let mint = StellarAssetClient::new(&env, &token_addr);
    let tok = TokenClient::new(&env, &token_addr);

    // REAL verifier loaded with the withdraw circuit's verifying key.
    let mut ic = Vec::new(&env);
    for e in f::VK_IC.iter() {
        ic.push_back(BytesN::from_array(&env, e));
    }
    let vk = molfi_verifier::VerifyingKey {
        alpha_g1: BytesN::from_array(&env, &f::VK_ALPHA),
        beta_g2: BytesN::from_array(&env, &f::VK_BETA),
        gamma_g2: BytesN::from_array(&env, &f::VK_GAMMA),
        delta_g2: BytesN::from_array(&env, &f::VK_DELTA),
        ic,
    };
    let verifier = env.register(molfi_verifier::Verifier, (admin.clone(), vk));

    let pool = env.register(PrivacyPool, (admin.clone(), verifier, token_addr.clone()));
    let pool_c = PrivacyPoolClient::new(&env, &pool);

    // A deposit funds the pool with collateral.
    let depositor = Address::generate(&env);
    mint.mint(&depositor, &100_000_000);
    pool_c.deposit(&depositor, &BytesN::from_array(&env, &[5u8; 32]), &100_000_000);
    assert_eq!(tok.balance(&pool), 100_000_000);

    // Operator checkpoints the circuit's (off-chain) Merkle root.
    let root = BytesN::from_array(&env, &f::PUBLIC[0]);
    pool_c.register_root(&root);

    // The real proof + its public signals [root, nullifierHash, recipient, amount].
    let proof = molfi_privacy_pool::Proof {
        a: BytesN::from_array(&env, &f::PROOF_A),
        b: BytesN::from_array(&env, &f::PROOF_B),
        c: BytesN::from_array(&env, &f::PROOF_C),
    };
    let mut sigs = Vec::new(&env);
    for s in f::PUBLIC.iter() {
        sigs.push_back(BytesN::from_array(&env, s));
    }

    // Withdraw to a fresh address — unlocked ONLY by the genuine proof.
    let recipient = Address::generate(&env);

    // Amount binding: paying a different amount than the proof authorizes fails.
    assert!(
        pool_c.try_withdraw(&proof, &sigs, &recipient, &50_000_000).is_err(),
        "amount not matching the proof must be rejected"
    );

    pool_c.withdraw(&proof, &sigs, &recipient, &100_000_000);
    assert_eq!(tok.balance(&recipient), 100_000_000, "real ZK proof unlocked the withdrawal");

    let nullifier = BytesN::from_array(&env, &f::PUBLIC[1]);
    assert!(pool_c.is_nullifier_used(&nullifier), "nullifier burned");

    // Same nullifier can't be spent twice.
    assert!(
        pool_c.try_withdraw(&proof, &sigs, &recipient, &100_000_000).is_err(),
        "double-spend rejected"
    );
}
